# Generated by Django 5.0.2 on 2024-03-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
