# Generated by Django 5.0.2 on 2024-03-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_tweet_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='is_liked',
        ),
    ]
