# Generated by Django 5.0.2 on 2024-03-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_tweet_dislikes_tweet_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
    ]
