# Generated by Django 5.0.2 on 2024-03-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_comment_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
